### ISSUE TITLE
How to deal with complex equations?

### ISSUE THREAD

**Issue by nickeltingupta** [mikelehu/IRK.jl#53]
It appears that IRKGaussLegendre.jl does not work with complex equations. For example, the following MWE results in `MethodError: no method matching isless(::ComplexF64, ::Float64)`. 

```
function simpleprob!(du::Vector{Complex{Float64}}, u::Vector{Complex{Float64}}, p, t)
    du[1] = u[2]
    du[2] = -im*u[1]
end

u0=[1.0+0.0im,0.0+0.0im]

prob1 = ODEProblem(simpleprob!,u0,(0.0,1.0),nothing)
sol1 = solve(prob1,IRKGL16())
```

**Comment by mikelehu** [comment]
You are right, RKGaussLegendre.jl fails with complex equations.
We will need some time to correct the error.

I'm sorry for the inconvenience and I hope we can resolve it soon.

**Comment by mikelehu** [comment]
- Now, IRKGaussLegendre.jl works well with complex equations. You must upgrade to v0.2.5 release:
    pkg>up IRKGaussLegendre

 - I have checked it with a new notebook called "/Examples/Office example using complex numbers (Github).ipynb" where I have coded the nbody problem with complex variables z=x+iy
